### ISSUE TITLE
这个redis cluster是从redis里面拔出来的？

### ISSUE THREAD

**Issue by lidaohang** [dennisip86/redis_cluster#1]
这个redis cluster是从redis里面拔出来的？你们是不是自己做了个代理，然后获取slot信息

**Comment by dennisip86** [comment]
你好:
    这个redis_cluster是基于hiredis写的，不是代理程序。slot信息是通过执行cluster slots返回的信息分析获取的。



dennisip_dvp@yahoo.com
 
发件人： daohang
发送时间： 2015-07-13 18:14
收件人： dennisip86/redis_cluster
主题： [redis_cluster] 这个redis cluster是从redis里面拔出来的？ (#1)
这个redis cluster是从redis里面拔出来的？你们是不是自己做了个代理，然后获取slot信息

**Comment by lidaohang** [comment]
哦，哦～　　我想自己做个代理程序，其实也就是从
ｒｅｄｉｓ上面执行cluster slots拿到槽对应的节点信息，   这个槽和节点信息都是存储在redis的每个节点上的吧！

**Comment by dennisip86** [comment]
是的

 
发件人： daohang
发送时间： 2015-07-14 13:06
收件人： dennisip86/redis_cluster
抄送： dennisip
主题： Re: [redis_cluster] 这个redis cluster是从redis里面拔出来的？ (#1)
哦，哦～　　我想自己做个代理程序，其实也就是从
ｒｅｄｉｓ上面执行cluster slots拿到槽对应的节点信息， 这个槽和节点信息都是存储在redis的每个节点上的吧！

**Comment by lidaohang** [comment]
是不是redis cluster里面的每个redis实例都存储着cluster slots  槽对应的节点信息。
如果我用nginx 开发给proxy，启动的时候把槽对应的节点信息都加载到nginx内存中
客户端请求过来，根据槽和对应的redis节点找到当前key对应的节点信息，然后去后端节点服务器请求

**Comment by dennisip86** [comment]
是的,但是要注意处理MOVE和ASK,详细的可以上redis.io或者中文版redisdoc.com查看文档.
 
发件人： daohang
发送时间： 2015-07-14 14:23
收件人： dennisip86/redis_cluster
抄送： dennisip
主题： Re: [redis_cluster] 这个redis cluster是从redis里面拔出来的？ (#1)
是不是redis cluster里面的每个redis实例都存储着cluster slots 槽对应的节点信息。
如果我用nginx 开发给proxy，启动的时候把槽对应的节点信息都加载到nginx内存中
客户端请求过来，根据槽和对应的redis节点找到当前key对应的节点信息，然后去后端节点服务器请求

**Comment by lidaohang** [comment]
那每个redis节点都维护一套槽和节点信息，他们之间是保存同步的吗？ 
为不为出现不一致的情况~
你说的这个move，和ask  是要单独特殊处理的，  但是如果我把槽信息都加载到nginx内存中了， 一般情况不会出现move，除非槽信息有变动，nginx内存的数据没及时更新
还有mget，mset也需要特殊处理

**Comment by lidaohang** [comment]
非常感谢你的回复

**Comment by dennisip86** [comment]
当一个从节点转换成主节点时，他会通知集群内所有节点，其他节点会更新对应信息的，这点不用担心。
请注意mget与mset等能够输入多个key的命令可以使用的前提是相同slot，而不是相同的节点；你能够分别使用{a}key1 {a}key2 用作key，这时他们将会以大括号内的a来计算slot。

不用客气，希望能够对你有帮助。

**Comment by lidaohang** [comment]
mget mset不一定要在相同的slot吧， 可能就需要访问多个节点
你的意思是给一个tab标记，然后以tag来crc16计算slot，从而避免了多个key在不同slot的问题

**Comment by dennisip86** [comment]
如果以mget或mset直接传给redis服务器，假如不是同一个slot的key，会返回一个错误CROSSSLOT Keys in request don't hash to the same slot。除非把mget每个key拆分成get key1、get key2的形式。

可以这么理解，而这个也是在redis服务器内同样是这样处理的，所以如果你需要写代理程序就要注意这个问题。

**Comment by lidaohang** [comment]
redis内部就用{a}key {a}key1 通过计算a来让这两个key在同一个slot的吧

**Comment by lidaohang** [comment]
嗯，这是个问题，我还在想，把key拆开来做，想了下，还是您说的这种方式比较靠谱，性能也不会有太大影响

**Comment by lidaohang** [comment]
您好，我用nginx upstream开发redis cluster的代理端， 貌似协议比较麻烦~  
例如： 我要去从后端redis里面获取slot信息及节点信息
cluster slots
*3\r\n

*4\r\n:0\r\n:5460\r\n
*2\r\n$9\r\n127.0.0.1\r\n:7000\r\n
*2\r\n$9\r\n127.0.0.1\r\n:7003\r\n

*4\r\n:10923\r\n:16383\r\n
*2\r\n$9\r\n127.0.0.1\r\n:7002\r\n
*2\r\n$9\r\n127.0.0.1\r\n:7005\r\n

*4\r\n:5461\r\n:10922\r\n
*2\r\n$9\r\n127.0.0.1\r\n:7001\r\n
*2\r\n$9\r\n127.0.0.1\r\n:7004\r\n

感觉在proxy里面在自己写redis协议解析比较麻烦，不知道您那边是从官网扒出来的还是？ 感觉扒出来也比较麻烦~ 想请教下您！ 期待您的回复~ 感谢了~

**Comment by dennisip86** [comment]
协议的构造与解析是利用hiredis来完成的，不需要自己另外写。
如果你不想用hiredis你可以下载他的源码下来看看自己封装一套，如果想使用hiredis的话可以看看redis_cluster/redis_cluster.c 中的_redis_cluster_refresh_from_reply函数。

**Comment by lidaohang** [comment]
您的意思就是把hiredis编译进去，然后只是利用他的redis协议这块， 
因为我的nginx upstream 自己发起请求到后端， 根本不需要hiredis来请求

**Comment by dennisip86** [comment]
如果是这样的话建议你看一下hiredis里面是怎么解析协议的，把他的接口复制到你的代码当中再来做内容的解析。

**Comment by lidaohang** [comment]
嗯，嗯~  好的~ 感谢了，我下午好好看看hiredis源码，然后把协议部分扣出来~

**Comment by lidaohang** [comment]
您好，ngx_http_redis_process_header
upstream 读后端redis的数据，怎么才知道读完了没？ 以前http 是一个hander的长度，根据这个长度，来对比知道读了多少~ 但是redis协议里面没有这样的~
如果遇到大value， 我怎么判断才能把value读完，然后解析解析处理包装~

**Comment by dennisip86** [comment]
redis的通讯协议能共通过 “数量+（长度+内容）* 数量“ 知道每一个请求数据的大小，跟http协议的解析方法是差不多的，详细的可以参考以下中文文档就一目了然了:
http://redisdoc.com/topic/protocol.html

**Comment by lidaohang** [comment]
感谢您的回复，我大致压测了下nginx，单核 后端一个redis实例

ab 压测只能到3w左右， nginx单个work的cpu接近90%
redis可以到4w的qps，为啥ngx_redis_upstream只能到3w左右？
